### ISSUE TITLE
dependency-management plugin breaks intellij plugin

### ISSUE THREAD

**Issue by eprst** [spring-gradle-plugins/dependency-management-plugin#93] opened 2016-06-21 16:56 UTC
Hi. I have a project which uses https://github.com/JetBrains/gradle-intellij-plugin and it seems to break as soon as I try to use dependency-management-plugin to it. Works just fine without it:

> gradle dependencies --configuration compile

    :idea-plugin:dependencies
    
    ------------------------------------------------------------
    Project :idea-plugin
    ------------------------------------------------------------
    
    compile - Dependencies for source set 'main'.
    \--- com.jetbrains:idea:2016.1.3
    
    BUILD SUCCESSFUL

Now if I add just one line: 
```
apply plugin: 'io.spring.dependency-management'
```
It fails with this:

    :idea-plugin:dependencies FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':idea-plugin:dependencies'.
    > Could not resolve all dependencies for configuration 'detachedConfiguration6'.
       > Module version xxx:idea-plugin:0.0.SNAPSHOT, configuration 'detachedConfiguration6' declares a dependency on configuration 'default' which is not declared in the module descriptor for com.jetbrains:idea:2016.1.3

Any ideas what can be wrong?
Thanks!

**Comment by wilkinsona** [comment] 2016-06-22 13:34
This looks like a duplicate of #46 which is caused by a limitation in Gradle. I'll have another look and see if there's anything I can do about it. If not, hopefully the workaround described in #46 will help.

**Comment by wilkinsona** [comment] 2016-06-22 15:54
As far as I can tell, the root cause in this cause is the Intellij plugin's creation of an `ivy.xml` file that doesn't declare a `default` configuration. I can't see a good way to avoid that causing problems. Your best bet is probably to use the workaround described above.

**Closed by wilkinsona** 2016-06-22 15:54 UTC

**Comment by eprst** [comment] 2016-06-22 18:24
Suggested workaround works, thanks
