### ISSUE TITLE
NullPointerException in ProjectPropertySource when a Project has a property with a null value

### ISSUE THREAD

**Issue by henrik242** [spring-gradle-plugins/dependency-management-plugin#206] opened 2018-03-07 14:46 UTC
When upgrading from 1.5.9 to 1.5.10, we get a NPE saying `Failed to resolve imported Maven boms: null`.  The error is the same with jdk8 and jdk9.

```
Caused by: java.lang.NullPointerException
        at io.spring.gradle.dependencymanagement.internal.properties.ProjectPropertySource.getProperty(ProjectPropertySource.java:45)
        at io.spring.gradle.dependencymanagement.internal.properties.ProjectPropertySource.getProperty(ProjectPropertySource.java:27)
        at io.spring.gradle.dependencymanagement.internal.properties.CompositePropertySource.getProperty(CompositePropertySource.java:43)
        at io.spring.gradle.dependencymanagement.internal.maven.PropertySourceValueSource.getValue(PropertySourceValueSource.java:38)
```

Here's the full stacktrace: [stacktrace.txt](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/1789496/stacktrace.txt)

**Comment by stigkj** [comment] 2018-03-07 15:09
This seems to be fixed in Spring Boot v2.

**Comment by wilkinsona** [comment] 2018-03-07 15:17
PropertyPropertySource hasn't changed recently so it's not immediately apparent why moving from Spring Boot 1.5.9 (Dependency Management Plugin 1.0.3) to Spring Boot 1.5.10 (Dependency Management Plugin 1.0.4) would cause a problem. The code in question is this:

```
    @Override
    public String getProperty(String name) {
        if (!this.project.hasProperty(name)) {
            return null;
        }
        return this.project.property(name).toString();
    }
```

Line 45 is the return statement. For it to NPE, `this.project.property(name)` would have to return `null`, despite `this.property.hasProperty(name)` having returned `true`. As things stand, I don't understand that.

Can you please provide a small sample that reproduces the problem?

**Comment by henrik242** [comment] 2018-03-08 08:18
I figured I indeed have an issue where `this.project.hasProperty(name) == true` and `this.project.property(name) == null`.  So the property exists with a value of null and the `getProperty` method should check for this.  I created a PR in #207

**Comment by henrik242** [comment] 2018-03-08 08:53
The problem was triggered by setting `ext['something'] = null` in build.gradle.

**Comment by wilkinsona** [comment] 2018-03-08 10:25
Closing in favour of the PR (#207).

**Closed by wilkinsona** 2018-03-08 10:25 UTC
