### ISSUE TITLE
VersionConfiguringAction should honor previous resolution strategy

### ISSUE THREAD

**Issue by sarhanm** [spring-gradle-plugins/dependency-management-plugin#102] opened 2016-07-29 16:58 UTC
[VersionConfiguringAction Line 68](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/master/src/main/groovy/io/spring/gradle/dependencymanagement/VersionConfiguringAction.groovy#L68)

I want to use the exclusion features of this plugin but I have my own resolution strategy. I was able to plugin my own strategy successfully via the `DependencyManagementExtension` but the `VersionConfiguringAction` is overriding the resolved version. 

In the` VersionConfiguringAction`, the `DependencyResolveDetails.target` will always contain the most recent resolved version, while `DependencyResolveDetails.requested` will always contain the originally requested version. 

Calling `useVersion` with the same version as `DependencyResolveDetails.requested.version` is wrong because you override a previously resolved version that existed in `DependencyResolveDetails.target`.

**Comment by wilkinsona** [comment] 2016-07-30 06:29
This change seems rather specific to your use case and may be a breaking change for others. People may be relying on dependency management overriding earlier resolution strategies.

Taking a step back, you've said that you want to " use the exclusion features of this plugin". If you don't configure any dependency management and set `overriddenByDependencies = false`, this plugin won't apply any version configuration. Does that meet your needs?

**Comment by sarhanm** [comment] 2016-07-30 19:53
Yes, that boolean does help. thanks for pointing it out.

I still think the change is valid. I can think of two scenarios

1. A person wants to completely override and nullify an earlier resolution strategy such that any change that the earlier strategy made is reversed/stomped on. This is what your plugin currently does.

2. A person wants to augment a resolution strategy. Layering them if you will. Such that each successive resolution strategy is updating the resolved version if that strategy was able to resolve it in some way and "passing" if no resolution was determined. This is what my pull request helps you do (to a degree since you would have to be looking at the target rather than the request for this to be true).

I'm unblocked at the moment, so i'll leave it up to you to decide how this should actually work. But its interesting that by using the `overriddenByDependencies` variable, you've shown that the preferred way to accomplish scenario number 1 is not to add a "terminal override" resolution strategy, but to use the boolean flag to selectively turn off the resolution strategy you don't want applied (or not to add it in the first place).

**Comment by sarhanm** [comment] 2016-08-01 03:34
So after testing this out using only your exclusion part of the plugin, I realized that its only half the solution. 

Looking at the code, the pom configurer is only applied for managed versions vs for all exclusions added to a ModuleDependency. Basically, the exclusions are properly excluded from the classpath, but are not correctly generated into the pom. This isn't a big deal since I can write my own configurer that adds those exclusions. 

Just an FYI and potentially an enhancement to your plugin.

**Comment by wilkinsona** [comment] 2016-08-01 07:45
> the pom configurer is only applied for managed versions vs for all exclusions added to a ModuleDpendency

That's by design.

AFAIK, Gradle will add exclusions to a generated pom as long as they're declared on a dependency (rather than a configuration) and each exclusion identifies a single artifact.

**Comment by wilkinsona** [comment] 2016-08-01 07:49
> completely override and nullify an earlier resolution strategy 

It doesn't do that. A resolution strategy does considerably more than just manage versions. It's only the version that's affected.

> selectively turn off the resolution strategy you don't want applied

Strictly speaking, it isn't being turned off. The boolean simply stops the versions declare on any dependencies from being part of dependency management. A knock-on effect of that is that there are no versions to be applied.

Given that the change you have proposed would be a breaking change and that you're no longer blocked, I'm going to close this. The cost of the change outweighs any benefit.

**Closed by wilkinsona** 2016-08-01 07:49 UTC
Labels: info required
