### ISSUE TITLE
Exclusions behaviour change with gradle 4

### ISSUE THREAD

**Issue by flozano** [spring-gradle-plugins/dependency-management-plugin#181] opened 2017-07-22 15:28 UTC
In my central BOM I have:
```xml
			<dependency>
				<groupId>org.quartz-scheduler</groupId>
				<artifactId>quartz</artifactId>
				<version>${quartz.version}</version>
				<exclusions>
					<exclusion>
						<groupId>com.zaxxer</groupId>
						<artifactId>HikariCP-java6</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
```

Then, I depend in one of my projects on it using:
```
compile group: 'org.quartz-scheduler', name: 'quartz'
```

When imported with this plugin into my gradle project and gradle 3.5, results in:
```
|    +--- org.quartz-scheduler:quartz: -> 2.3.0
|    |    +--- com.mchange:c3p0:0.9.5.2
|    |    |    \--- com.mchange:mchange-commons-java:0.2.11
|    |    +--- com.mchange:mchange-commons-java:0.2.11
|    |    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.25
```

However, when I upgrade to gradle 4.0.1, I get:
```
|    +--- org.quartz-scheduler:quartz: -> 2.3.0
|    |    +--- com.mchange:c3p0:0.9.5.2
|    |    |    \--- com.mchange:mchange-commons-java:0.2.11
|    |    +--- com.mchange:mchange-commons-java:0.2.11
|    |    +--- com.zaxxer:HikariCP-java6:2.3.13
|    |    |    \--- org.slf4j:slf4j-api:1.7.10 -> 1.7.25
|    |    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.25
```
but only in the `testArtifacts`, `testCompileClasspath`, `testRuntimeClasspath`. In the `main`, `runtime` and such, the exclusion still applies.

**Comment by wilkinsona** [comment] 2017-07-22 18:45
This is caused by a [regression in Gradle](https://github.com/gradle/gradle/issues/2480). I believe it'll be fixed in Gradle 4.0.2.

**Closed by wilkinsona** 2017-07-22 18:45 UTC

**Comment by flozano** [comment] 2017-07-23 02:15
oh, ok, sorry for the inconvenience of reporting it here, and thanks for the hint.

**Comment by raniejade** [comment] 2017-07-24 06:53
Fix is included in Gradle `4.1-rc-1`, but this plugin totally breaks Gradle Sync in IntelliJ IDEA. Disabling the plugin fixes it and the issue is not happening pre 4.x.

**Comment by wilkinsona** [comment] 2017-07-24 07:14
@raniejade Please report the problem to the Gradle team

**Comment by wilkinsona** [comment] 2017-07-24 08:40
@raniejade It would also be helpful to provide a complete `build.gradle` that reproduces the problem. I have been unable to do so thus far.

**Comment by raniejade** [comment] 2017-07-24 10:53
@wilkinsona Here's a sample `build.gradle`:

```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }

    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:1.0.3.RELEASE'
    }
}

apply plugin: 'io.spring.dependency-management'
apply plugin: 'java'
apply plugin: 'idea'

dependencyManagement {
    dependencies {
        dependency "com.github.zafarkhaja:java-semver:0.9.0"

        dependencySet(group: 'io.dropwizard.metrics', version: '3.1.0') {
            entry ('metrics-core') {
                exclude 'org.slf4j:slf4j-api'
            }
            entry ('metrics-jvm') {
                exclude 'org.slf4j:slf4j-api'
                exclude 'io.dropwizard.metrics:metrics-core'
            }
            entry ('metrics-graphite') {
                exclude 'org.slf4j:slf4j-api'
                exclude 'io.dropwizard.metrics:metrics-core'
            }
        }

        dependency 'org.slf4j:slf4j-api:1.7.12'
    }
}


repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.slf4j:slf4j-api'

    compile 'com.github.zafarkhaja:java-semver'
    compile 'io.dropwizard.metrics:metrics-core'
}
```

Interestingly when I change `compileOnly 'org.slf4j:slf4j-api'` to `compile`, importing works. The config above excludes ` io.dropwizard.metrics:metrics-core` transitive dependencies since I want to specify my own version.

**Comment by wilkinsona** [comment] 2017-07-24 12:40
@raniejade Thanks. I've opened https://github.com/gradle/gradle/issues/2573 as I suspect this is a regression in 4.1-rc-1 and, as such, it needs to be looked at by the Gradle team.

**Comment by raniejade** [comment] 2017-07-24 13:39
Thanks @wilkinsona!

**Comment by bigdaz** [comment] 2017-07-24 22:19
Thanks for the report. The second regression (gradle/gradle#2573) was actually introduced as part of the fix for the main issue reported here (#181).

 Luckily the problem was caught in time, and it will be fixed in both `4.1-rc-2` and `4.0.2`.

**Comment by jjohannes** [comment] 2017-07-25 15:10
@raniejade @wilkinsona I have created snapshots of the soon to be published `4.0.2` and of what will most likely become `4.1 RC2`. Would you mind giving it a spin? In particular for `4.0.2`, I want to make sure that this version is working for you before releasing the hotfix. Thanks!

- [4.0.2-20170725142320+0000](https://services.gradle.org/distributions-snapshots/gradle-4.0.2-20170725142320+0000-bin.zip)
- [4.1-20170725144305+0000](https://services.gradle.org/distributions-snapshots/gradle-4.1-20170725144305+0000-bin.zip)

**Comment by wilkinsona** [comment] 2017-07-25 19:41
@jjohannes Both the sample shared above and the one I shared in gradle/gradle#2573 work with both those snapshots

**Comment by eriwen** [comment] 2017-07-25 19:50
Awesome. Thanks so much for your help @wilkinsona! 💯

**Comment by raniejade** [comment] 2017-07-26 05:13
It's working for our project as well. Thanks!

**Comment by flozano** [comment] 2017-07-28 08:26
working here too with 4.0.2
