### ISSUE TITLE
Provide docs why native Gradle BOM support is not sufficient

### ISSUE THREAD

**Issue by gavenkoa** [spring-gradle-plugins/dependency-management-plugin#243] opened 2019-02-23 21:20 UTC
I understand why we had plugin in a past:

* https://spring.io/blog/2015/02/23/better-dependency-management-for-gradle

But it is unclear benefits at present:

* https://docs.gradle.org/4.6/release-notes.html#bom-import with `enableFeaturePreview('IMPROVED_POM_SUPPORT')`
* https://gradle.org/whats-new/gradle-5/ *Platform definitions, aka Maven BOM dependencies are natively supported, allowing importing things like the Spring Boot platform definition without using an external plugin*

I've read some bug reports and there wasn't agreement on BOM semantic in Gradle and Spring teams, am I wrong?

* https://github.com/gradle/gradle/issues/1162

Please update docs and README.md  to make it clear whether I need this plugin or not with modern Gradle?

**Comment by wilkinsona** [comment] 2019-02-24 13:00
Duplicate of #211.

**Closed by wilkinsona** 2019-02-24 13:00 UTC
