### ISSUE TITLE
allow publishing artifacts with hard-coded dependencies versions and not with dependency management

### ISSUE THREAD

**Issue by ItamarBenjamin** [spring-gradle-plugins/dependency-management-plugin#215] opened 2018-06-07 07:40 UTC
although my projects use dependency management plugin, my clients may not be using this. i would like that every dependency in my published pom file will be published with version specified in the bom and not with a block of dependecyManagement.

i tried using 
`dependencyManagement {
    generatedPomCustomization {
        enabled = false
    }
}`

but that just removed the dependecyManagement block from the pom file, it did not add the resolved version to every dependency

**Comment by wilkinsona** [comment] 2018-06-08 12:38
> although my projects use dependency management plugin, my clients may not be using this

If the dependency management is included in a module's pom file, a consumer of that module (either in Maven or Gradle) will always use its dependency management when resolving the module's dependencies.

With this in mind, I'm not sure that there's any real benefit to hard-coding the versions vs using a dependency management block. Have I missed something?

**Comment by ItamarBenjamin** [comment] 2018-06-11 13:56
Hi @wilkinsona and thank you for the quick answer.

I didn't know that gradle support depdencyManagement natively but still we're experiencing issues with ordering. My real case is as follows:
1. I have two services, A publishes its api and B consumes it.
2. Since services A and B are spring based, they both use the dependency management plugin.
3. service A api's is published with Bom version x, and service B imports with the plugin Bom version y.
4. I would expect all the the build to use service B's bom's version, but instead the api's bom takes precedence. 

thanks

**Comment by wilkinsona** [comment] 2018-06-13 16:23
Thanks for the additional details. I'd expect the bom import in service B to override whatever's in the pom for service A. Can you please provide a minimal example that reproduces the structure and behaviour that you have described?

**Comment by wilkinsona** [comment] 2018-07-17 14:37
It's been just over a month now with no reply. Closing due to required information not being provided.

**Closed by wilkinsona** 2018-07-17 14:37 UTC
Labels: info required
