### ISSUE TITLE
An exclusion in a bom for a dependency that cannot be resolved is not applied

### ISSUE THREAD

**Issue by scottresnik** [spring-gradle-plugins/dependency-management-plugin#118] opened 2016-09-23 20:55 UTC
I have created a pom for my parent project, and it includes some exclusion in some of the dependencies.  I've noticed that those exclusions are not processed.  The documentation says that exclusions are processed by explicit dependencies, but it doesn't mention anything about imported boms.  Is this lack of processing of exclusions in bom's by design?

**Comment by wilkinsona** [comment] 2016-09-24 15:05
Exclusions from a bom should be processed. There are tests for excluding both [direct](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/master/src/test/groovy/io/spring/gradle/dependencymanagement/DependencyManagementPluginSpec.groovy#L826) and [transitive](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/master/src/test/groovy/io/spring/gradle/dependencymanagement/DependencyManagementPluginSpec.groovy#L850) dependencies using a bom.

If you believe you've found a case where this isn't work then please provide a sample that reproduces the problem and I'll take a look

**Comment by scottresnik** [comment] 2016-09-26 17:08
What if the dependency to be excluded does not exist in any configured repository?  Does the plugin attempt to download the dependency before applying the exclusion?

I've created a small project to illustrate: https://github.com/scottresnik/depmgmt-118

To reproduce:
1. Execute `gradlew publishToMavenLocal` in parent.
2. Execute `gradlew build` in child.

You should get the following:
```
* What went wrong:
Could not resolve all dependencies for configuration 'detachedConfiguration2'.
> Could not find adaptx:adaptx:0.9.13.
  Searched in the following locations:
      https://jcenter.bintray.com/adaptx/adaptx/0.9.13/adaptx-0.9.13.pom
      https://jcenter.bintray.com/adaptx/adaptx/0.9.13/adaptx-0.9.13.jar
      https://repo1.maven.org/maven2/adaptx/adaptx/0.9.13/adaptx-0.9.13.pom
      https://repo1.maven.org/maven2/adaptx/adaptx/0.9.13/adaptx-0.9.13.jar
      file:/C:/Users/scott/.m2/repository/adaptx/adaptx/0.9.13/adaptx-0.9.13.pom
      file:/C:/Users/scott/.m2/repository/adaptx/adaptx/0.9.13/adaptx-0.9.13.jar
  Required by:
      :child:unspecified > org.codehaus.castor:castor:1.0.5
```

I know this is a corner case since I'm dealing with an old(~10 years) dependency.

**Comment by wilkinsona** [comment] 2016-09-27 15:15
Got it now, thank you.

I think this can be fixed by giving special consideration to dependencies that can't be resolved when figuring out what should and should not be excluded.

**Comment by scottresnik** [comment] 2016-09-27 15:27
Thanks @wilkinsona .

**Comment by wilkinsona** [comment] 2016-09-27 20:12
@scottresnik Your sample works for me now with 0.6.2.BUILD-SNAPSHOT that's available from https://repo.spring.io/plugins-snapshot. Can you please give it a try on your proper project and confirm that it works there too?

**Comment by scottresnik** [comment] 2016-09-28 13:44
My proper project required a few minor dependency declaration clean up, but it seems to be functioning now with 0.6.2.BUILD-SNAPSHOT.

Before the dependency changes, even with 0.6.2, there were cases where the exclusions were not processing.  I attempted to reproduce them with my example but was unable to.  In the end, making sure that a dependency was only declared once throughout all of my interdependent sub projects cured the issue.

Thanks for the quick turn around, @wilkinsona .

**Comment by scottresnik** [comment] 2016-09-28 14:05
I forgot to mention that there is some debugging output in the latest snapshot of the plugin.  Will that removed in the final release?  Below is an example.
```
Excluding {module=some-module, group=some.group} from DefaultExternalModuleDependency{group='another.group', name='another-module', version='null', configuration='default'}
```

**Comment by wilkinsona** [comment] 2016-09-28 14:48
Whoops. That shouldn't have been committed in the first place. Thanks for spotting it.

**Comment by wilkinsona** [comment] 2016-10-26 13:29
This fix appears to be incomplete. Here's a sample from @vtajzich that doesn't work even once it's been updated to use 0.6.2 snapshots: https://dl.dropboxusercontent.com/u/1740442/demo.zip

**Closed** 2016-11-04 16:28 UTC
Labels: bug
