### ISSUE TITLE
can no longer exclude faulty poms in 0.6.0 and 0.6.1

### ISSUE THREAD

**Issue by gregallen** [spring-gradle-plugins/dependency-management-plugin#119] opened 2016-10-04 16:43 UTC
see also issue #98 

similar failure here, though in my case owing to a fragmentary & invalid pom in a local repository.

Failure occurs in 0.6.0 and 0.6.1 releases. No issues in 0.5.6.

In the newer releases using exclusions to stay away from the faulty pom no longer works.

stacktrace:

    at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.findExcludedDependencies(ExclusionConfiguringAction.java:124)
    at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.applyMavenExclusions(ExclusionConfiguringAction.java:96)
    at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.execute(ExclusionConfiguringAction.java:90)
    at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.execute(ExclusionConfiguringAction.java:51)
root cause:
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException
at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:83)

**Comment by wilkinsona** [comment] 2016-10-04 19:42
@gregallen A stack trace doesn't tell me much at all about what you've tried. Can you share a small project that reproduces your problem?

**Comment by wilkinsona** [comment] 2016-10-26 13:27
Closing due to the lack of required information. @gregallen if you can put together a sample project as requested above we can re-open this issue.

**Closed by wilkinsona** 2016-10-26 13:27 UTC
Labels: info required
