### ISSUE TITLE
Plugin does not work as expected

### ISSUE THREAD

**Issue by dengayevskiy** [spring-gradle-plugins/dependency-management-plugin#150] opened 2017-02-24 01:05 UTC
I have multi module project and trying to apply dependency-management-plugin like that:

**root build.gradle**
```
def testProjects = [project(':casino-tests'), project(':slotomania-tests')]
def allProjects = testProjects + [project(':common')]

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:1.0.0.RELEASE"
    }
}

configure(allProjects) {
    apply plugin: "io.spring.dependency-management"
    apply plugin: 'idea'
    apply plugin: 'java'
    apply plugin: 'groovy'

    repositories {
        maven { url "http://artifactory.corp/artifactory/repo" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
        maven { url "http://dl.bintray.com/anotherchrisberry/spock-retry" }
        maven { url "https://repo.spring.io/libs-release-local" }
    }
}
```
**child build.gradle (common)** 

```
dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-starter-parent:1.4.1.RELEASE'
    }
}
dependencies {
    compile 'org.springframework.boot:spring-boot-starter-websocket'
    compile(group: 'org.springframework.boot', name: 'spring-boot-starter-test')
    compile(group: 'org.springframework.boot', name: 'spring-boot-starter-actuator')
}
```
Also tried such option:

```
dependencyManagement {
    dependencies {
        dependency 'org.springframework.boot:spring-boot-starter-test:1.4.1'
        dependency 'org.springframework.boot:spring-boot-starter-actuator:1.4.1'
        dependency 'org.springframework.boot:spring-boot-starter-websocket:1.4.1'
    }
}
```

But result is always the same: 
<img width="553" alt="screen shot 2017-02-24 at 2 59 33" src="https://cloud.githubusercontent.com/assets/7139091/23285994/5b86ad46-fa3d-11e6-95ed-20adf894dbaa.png">

I've tried with Gradle 3.2.1 and 3.4

**Comment by wilkinsona** [comment] 2017-02-24 09:51
Sorry, but a screenshot with some red underlines doesn't really tell me anything. It's also from an IDE which introduces the possibility that the problem lies there rather than in Gradle or this plugin.

What steps do I need to take to reproduce the problem you're seeing without involving an IDE? A Git repository that I can clone and run would be much better than trying to piece things together from some snippets shared here.

**Comment by wilkinsona** [comment] 2017-03-09 17:07
It's been two weeks since this was opened and no extra information has been provided so I'm going to close this issue. If you provide the requested information, I'll re-open the issue and take a look.

**Closed by wilkinsona** 2017-03-09 17:07 UTC
Labels: info required

**Comment by dengayevskiy** [comment] 2017-07-14 14:19
I think you spent more time writing this answer to me than it would took to create a sample project in IDE and copy/paste there content of provided _build.gradle_ files. 

I've already used another plugin. Thank you.
