### ISSUE TITLE
dependency-mangement block is not being applied.

### ISSUE THREAD

**Issue by from-nibly** [spring-gradle-plugins/dependency-management-plugin#73] opened 2016-02-09 18:34 UTC
I have an application that is not accepting dependency management from the dependencyManagement block.

this happens
```
11:23:00.949 [INFO] [io.spring.gradle.dependencymanagement.DependencyManagementPlugin] Applying dependency management to configuration 'jacocoAgent' in project '<my-project>'
```
then i get this for some reason

```
11:23:20.682 [DEBUG] [io.spring.gradle.dependencymanagement.VersionConfiguringAction] Processing dependency 'org.jacoco:org.jacoco.agent:'
11:23:20.682 [DEBUG] [io.spring.gradle.dependencymanagement.VersionConfiguringAction] No dependency management for dependency 'org.jacoco:org.jacoco.agent:'
```

I am normally getting this dependencyManagement from a plugin i am applying but i have tried putting it right above the dependencies block.

This project is a submodule of another submodule.

in the root project there is a dependency management block
```groovy
subprojects { proj ->
    dependencyManagement {
    }
}
```

**Comment by wilkinsona** [comment] 2016-02-09 19:11
Unfortunately, I can't offer any concrete suggestions without some more information. How is the dependency management for `org.jacoco:org.jacoco.agent` being configured? Is it being configured globally or for a particular configuration? If it's the latter, does the `jacooAgent` configuration inherit from that configuration? Perhaps you could answer these questions by providing a small sample project?

**Comment by from-nibly** [comment] 2016-02-09 19:45
_how is it being configured?_
i have tried the following

I am applying a plugin inside an allprojects block. 
```groovy
//project/build.gradle
allprojects {
    apply plugin: 'my-plugin'
}
```
The plugin has the following code.
```groovy
//plugin/plugin.groovy
void apply(Project project) {
        project.dependencyManagement {
            dependencies {
                dependency "org.jacoco:org.jacoco.agent:0.7.1.201405082137"
            }
        }
}
```
This applies it to each project individually.

I have also tried applying it right inside the subprojects build.gradle
```groovy
//project/subproject/build.gradle
dependencyManagement {
    dependencies {
        dependency "org.jacoco:org.jacoco.agent:0.7.1.201405082137"
    }
}
dependencies {
    compile("org.jacoco:org.jacoco.agent")
}
```
This would apply it right before the dependency block.

there is also a dependency management block inside the root project in a subproject block
```
//project/build.gradle
subprojects { proj ->
    dependencyManagement {
    //jacoco agent is not here
    }
}
```

I'll try to get a working sample project together. I guess another question is. Is there any way the dependencyMangement could be overridden or lost somehow or an individual entry to be cleared?

**Comment by from-nibly** [comment] 2016-02-09 20:18
*UPDATE:*
I downgraded my gradle version from 2.6 to 1.12 and everything works.

**Comment by wilkinsona** [comment] 2016-02-09 20:36
> Is there any way the dependencyMangement could be overridden or lost somehow or an individual entry to be cleared

Not that I'm aware of. For example, if you have multiple dependency management blocks for the same project they are additive.

> I downgraded my gradle version from 2.6 to 1.12 and everything works.

That's an interesting data point. Thanks. I'm not aware of any changes affecting dependency management. The plugin's built with Gradle 1.12 and is also tested against 2.4 to 2.10 inclusive.

I think I'm going to need a sample project to figure out why different versions of Gradle are causing different behaviour.

**Comment by checketts** [comment] 2016-02-18 18:46
@wilkinsona I worked with @from-nibly some as he was consuming a gradle plugin I had written to help apply the dependency management plugin. Since gradle says that applying plugins should be idempotent, I had a block to detect if my task already existed (or if the project had created their own version of my task, bypassing mine, like so: 

````
if(project.getTasksByName('someTask',false).isEmpty()){
  project.task('someTask'){
    //task stuff  
  }
}
````

However, that approach seemed to trigger an evaluation of all subprojects. By changing `project.getTasksByName('someTask',false).isEmpty()` to `project.tasks.findByPath('someTask') == null` it fix this behavior. So the root cause was a change in how Gradle did multiple passes evaluating projects (or something). At this point it looks like my plugin had broken your plugin, due to a behavior in Gradle. You can probably close this out (unless you have a technique to protect yourself from other plugins).

**Comment by wilkinsona** [comment] 2016-02-19 08:46
@checketts Thanks for following up. Can you point me to your plugin please? I'd like to see if I can reproduce the problem and then, if possible, add some protection to the dependency management plugin.

**Comment by wilkinsona** [comment] 2016-03-24 11:37
Closing as there's nothing that can be done without some information from @checketts.

**Closed by wilkinsona** 2016-03-24 11:37 UTC
Labels: info required
