### ISSUE TITLE
problem with java 9, gradle 4.2, spring 2.0.0.M4

### ISSUE THREAD

**Issue by norbitheeviljester** [spring-gradle-plugins/dependency-management-plugin#189] opened 2017-09-29 10:51 UTC
Hi,
I have a java project in which I'm trying to incorporate java 9, gradle 4.2 and spring 2.0.0M4. After switching to java 9 the dependency management plugin doesn't seem to be adding versions to my spring dependencies and they're not being found.

I've attached log from my gradle build
[log.txt](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/1344046/log.txt)
as well as the build.gradle file
[build.gradle.txt](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/1344050/build.gradle.txt)

my gradle wrapper uses:
distributionUrl=https\://services.gradle.org/distributions/gradle-4.2-all.zip

C:\Users\NogackiN\IdeaProjects\rokku>gradlew --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/NogackiN/.gradle/wrapper/dists/gradle-4.2-all/35kgqhc6h01n0g1he8zslvs9l/gradle-4.2/lib/groovy-all-2.4.11.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9 (Oracle Corporation 9+181)
OS:           Windows 10 10.0 amd64

**Comment by wilkinsona** [comment] 2017-09-29 10:54
Duplicate of #187.

**Closed by wilkinsona** 2017-09-29 10:54 UTC

**Comment by norbitheeviljester** [comment] 2017-09-29 10:55
sorry about that. Don't know how I missed it.
