### ISSUE TITLE
Using this plugin on Android project slows gradle sync by an order of magnitude

### ISSUE THREAD

**Issue by dalewking** [spring-gradle-plugins/dependency-management-plugin#78] opened 2016-03-24 19:52 UTC
Have applied this plugin to an Android project in Android Studio and have noticed that gradle synchronization is slower by an order of magnitude. Unfortunately, I can't give you access to the project to test it.

I looked in the log to see if there is anything there. The primary difference is between 2 steps in the log:

2016-03-24 15:41:58,291 [214822056]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 14ms; general responsiveness: ok; EDT responsiveness: ok 
2016-03-24 15:43:24,772 [214908537]   INFO -  #git4idea.commands.GitHandler - cd /Users/DALEK/Documents/MyProject

Without the plugin, those steps are separated by ~8 secs. With the plugin they are separated by almost 2-1/2 minutes

**Comment by wilkinsona** [comment] 2016-03-25 07:30
Unfortunately, diagnosing a performance problem that cannot be reproduced will be pretty much impossible. You haven't even said which version of the plugin you are using. If you'd like me to spend some time investigating, please spend some time producing a sample project that reproduces the issue.

**Comment by wilkinsona** [comment] 2016-03-25 07:32
Depending on the version you are using, https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/65 could be relevant here.

**Comment by dalewking** [comment] 2016-03-25 18:15
I am going to try to work on a stripped down project that demonstrates the issue. Have not been successful so far

**Comment by wilkinsona** [comment] 2016-04-15 08:00
Closing due to lack of required information. @dalewking If you manage to produce a stripped down project, please comment here and we can reopen the issue.

**Closed by wilkinsona** 2016-04-15 08:00 UTC
Labels: info required
