### ISSUE TITLE
The error report is confusing when a version property is invalid

### ISSUE THREAD

**Issue by leoedeng** [spring-gradle-plugins/dependency-management-plugin#196] opened 2017-12-08 01:48 UTC
```
buildscript {
        ext {
                springBootVersion = '1.5.9.RELEASE'
        }
        repositories {
                mavenCentral()
        }
        dependencies {
                classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        }
}
ext['spring.verion']='0.0'

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
        mavenCentral()
}

dependencies {
        compile("org.jetbrains.kotlin:kotlin-stdlib-jre8")
        compile('org.springframework.boot:spring-boot-starter')
        testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

With above build.gradle file, the `spring.version` property is invalid, but the error report is complaining about an irrelevant dependency.
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find org.jetbrains.kotlin:kotlin-stdlib-jre8:.
  Required by:
      project :
```

On the other hand, I have another kotlin project, which I accidentally set the `kotlin.version` to be null, and the error report is complaining about all other dependencies except for kotlin.

It'd be really helpful if the plugin can pinpoint the actual invalid dependencies.

**Comment by wilkinsona** [comment] 2017-12-08 18:51
I think this may be a duplicate of #175. When I investigated that issue, there was no way to get Gradle to produce better diagnostics due to it swallowing exceptions in certain places. Before closing this as a duplicate, I'll take another look to see if that's still the case or if there's anything else that could be done.

**Comment by wilkinsona** [comment] 2017-12-08 19:29
A second look proved worthwhile. With `spring.version` set to `0.0` (which breaks the Spring Boot bom's import of the Spring Framework bom) a build will now fail with the following message:

```
./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':detachedConfiguration7'.
> Could not find org.springframework:spring-framework-bom:0.0.
  Searched in the following locations:
      https://repo.maven.apache.org/maven2/org/springframework/spring-framework-bom/0.0/spring-framework-bom-0.0.pom
      https://repo.maven.apache.org/maven2/org/springframework/spring-framework-bom/0.0/spring-framework-bom-0.0.pom
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

Hopefully the appearance of `0.0` and a Spring Framework-related artifact in the message will be sufficient to diagnose the problem. It's certainly an improvement on the current behaviour.

**Closed** 2017-12-08 19:30 UTC
Labels: bug

**Comment by leoedeng** [comment] 2017-12-11 12:56
Thanks @wilkinsona.  I am looking forward to the next release.
