### ISSUE TITLE
Avoid applying dependency management to dependencies with a forced version

### ISSUE THREAD

**Issue by JLLeitschuh** [spring-gradle-plugins/dependency-management-plugin#167] opened 2017-04-20 19:27 UTC
I'm converting my company's app from a tomcat war to spring boot.

We have a fairly large list of dependencies in the root project that are forced using
 ```kotlin
configurations.all {
    resolutionStrategy {
         force("... forced dependencies ....")
    }
}
```
My dependencies are now totally different because the plugin doesn't honor these.
I tried adding these forces to:
```kotlin
dependencyManagement {
    resolutionStrategy {
        // Same list of forced dependencies
        force("... forced dependencies ....")
    }
}
```
but it seems like the resulting set of dependencies are still ignoring this as well.
Am I missing something? Is this an issue with the spring boot plugin not this one?

Relevant plugins with their versions
```
id("org.springframework.boot") version "1.5.2.RELEASE"
id("io.spring.dependency-management") version "1.0.2.RELEASE"
```

**Comment by wilkinsona** [comment] 2017-04-20 19:56
The second thing you tried certainly won't work. That resolution strategy is only used for the resolution of any Maven boms that have been imported. I think the first should work if you've ordered things correctly. Can you please provide a small sample that illustrates the problem you're seeing?

**Comment by JLLeitschuh** [comment] 2017-04-20 20:01
> I think the first should work if you've ordered things correctly.

Ordered correctly? I thought gradle didn't care about ordering?

**Comment by wilkinsona** [comment] 2017-04-20 20:03
No, Gradle does care about ordering. For example, the ordering of resolution strategies affects which one will win. If you'd like some more help, please provide a small sample that illustrates the problem you're seeing.

**Comment by JLLeitschuh** [comment] 2017-04-20 20:27
I'm working on a small demo project to try to reproduce the problem

**Comment by JLLeitschuh** [comment] 2017-04-20 20:51
Okay, so here's the demo project that demonstrates the problem (with the actual dependency I was having this problems with incidentally).

This is my minimalist `build.gradle.kts` file:
```kotlin
import org.gradle.api.tasks.wrapper.Wrapper

plugins {
    java
    id("org.springframework.boot") version "1.5.2.RELEASE"
    id("io.spring.dependency-management") version "1.0.2.RELEASE"
}
group = "org.jlleitschuh.boot-test"
version = "1.0-SNAPSHOT"

configurations.all {
    resolutionStrategy {
        // I explicitly set the version of logback classic that I want here, but it is ignored 😢
        force("ch.qos.logback:logback-classic:1.1.3")
    }
}

dependencies {
    compile(group = "org.springframework.boot", name = "spring-boot-starter-security")
    compile(group = "org.springframework.boot", name = "spring-boot-starter-tomcat")
}

repositories {
    mavenCentral()
}

springBoot {
    mainClass = "Application"
}


task<Wrapper>("wrapper") {
    distributionUrl = "https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.5-20170404014535+0000-all.zip"
    distributionType = Wrapper.DistributionType.ALL
}

/**
 * Retrieves or configures the [springBoot][org.springframework.boot.gradle.SpringBootPluginExtension] project extension.
 */
fun Project.springBoot(configure: org.springframework.boot.gradle.SpringBootPluginExtension.() -> Unit = {}) =
    extensions.getByName<org.springframework.boot.gradle.SpringBootPluginExtension>("springBoot").apply { configure() }
```

Running `./gradlew dependencies --configuration compile` with this project results in the following dependency output:
```
------------------------------------------------------------
Root project
------------------------------------------------------------

compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
+--- org.springframework.boot:spring-boot-starter-security: -> 1.5.2.RELEASE
|    +--- org.springframework.boot:spring-boot-starter:1.5.2.RELEASE
|    |    +--- org.springframework.boot:spring-boot:1.5.2.RELEASE
|    |    |    +--- org.springframework:spring-core:4.3.7.RELEASE
|    |    |    \--- org.springframework:spring-context:4.3.7.RELEASE
|    |    |         +--- org.springframework:spring-aop:4.3.7.RELEASE
|    |    |         |    +--- org.springframework:spring-beans:4.3.7.RELEASE
|    |    |         |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
|    |    |         |    \--- org.springframework:spring-core:4.3.7.RELEASE
|    |    |         +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
|    |    |         +--- org.springframework:spring-core:4.3.7.RELEASE
|    |    |         \--- org.springframework:spring-expression:4.3.7.RELEASE
|    |    |              \--- org.springframework:spring-core:4.3.7.RELEASE
|    |    +--- org.springframework.boot:spring-boot-autoconfigure:1.5.2.RELEASE
|    |    |    \--- org.springframework.boot:spring-boot:1.5.2.RELEASE (*)
|    |    +--- org.springframework.boot:spring-boot-starter-logging:1.5.2.RELEASE
|    |    |    +--- ch.qos.logback:logback-classic:1.1.11
|    |    |    |    +--- ch.qos.logback:logback-core:1.1.11
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.22 -> 1.7.24
|    |    |    +--- org.slf4j:jcl-over-slf4j:1.7.24
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.24
|    |    |    +--- org.slf4j:jul-to-slf4j:1.7.24
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.24
|    |    |    \--- org.slf4j:log4j-over-slf4j:1.7.24
|    |    |         \--- org.slf4j:slf4j-api:1.7.24
|    |    +--- org.springframework:spring-core:4.3.7.RELEASE
|    |    \--- org.yaml:snakeyaml:1.17
|    +--- org.springframework:spring-aop:4.3.7.RELEASE (*)
|    +--- org.springframework.security:spring-security-config:4.2.2.RELEASE
|    |    +--- org.springframework.security:spring-security-core:4.2.2.RELEASE
|    |    |    +--- org.springframework:spring-aop:4.3.5.RELEASE -> 4.3.7.RELEASE (*)
|    |    |    +--- org.springframework:spring-beans:4.3.5.RELEASE -> 4.3.7.RELEASE (*)
|    |    |    +--- org.springframework:spring-context:4.3.5.RELEASE -> 4.3.7.RELEASE (*)
|    |    |    +--- org.springframework:spring-core:4.3.5.RELEASE -> 4.3.7.RELEASE
|    |    |    \--- org.springframework:spring-expression:4.3.5.RELEASE -> 4.3.7.RELEASE (*)
|    |    +--- org.springframework:spring-aop:4.3.5.RELEASE -> 4.3.7.RELEASE (*)
|    |    +--- org.springframework:spring-beans:4.3.5.RELEASE -> 4.3.7.RELEASE (*)
|    |    +--- org.springframework:spring-context:4.3.5.RELEASE -> 4.3.7.RELEASE (*)
|    |    \--- org.springframework:spring-core:4.3.5.RELEASE -> 4.3.7.RELEASE
|    \--- org.springframework.security:spring-security-web:4.2.2.RELEASE
|         +--- org.springframework.security:spring-security-core:4.2.2.RELEASE (*)
|         +--- org.springframework:spring-beans:4.3.5.RELEASE -> 4.3.7.RELEASE (*)
|         +--- org.springframework:spring-context:4.3.5.RELEASE -> 4.3.7.RELEASE (*)
|         +--- org.springframework:spring-core:4.3.5.RELEASE -> 4.3.7.RELEASE
|         +--- org.springframework:spring-expression:4.3.5.RELEASE -> 4.3.7.RELEASE (*)
|         \--- org.springframework:spring-web:4.3.5.RELEASE -> 4.3.7.RELEASE
|              +--- org.springframework:spring-aop:4.3.7.RELEASE (*)
|              +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
|              +--- org.springframework:spring-context:4.3.7.RELEASE (*)
|              \--- org.springframework:spring-core:4.3.7.RELEASE
\--- org.springframework.boot:spring-boot-starter-tomcat: -> 1.5.2.RELEASE
     +--- org.apache.tomcat.embed:tomcat-embed-core:8.5.11
     +--- org.apache.tomcat.embed:tomcat-embed-el:8.5.11
     \--- org.apache.tomcat.embed:tomcat-embed-websocket:8.5.11
          \--- org.apache.tomcat.embed:tomcat-embed-core:8.5.11

(*) - dependencies omitted (listed previously)

BUILD SUCCESSFUL
```

Notice how the logback dependency version loaded is this:
```
ch.qos.logback:logback-classic:1.1.11
```
instead of the version that I've asked for.

I published the entire example source code here:
https://github.com/JLLeitschuh/springBootTesting

I've also uploaded the ZIP of the project.
[springBootTesting-master.zip](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/945450/springBootTesting-master.zip)

**Comment by wilkinsona** [comment] 2017-04-20 21:08
Thanks. Presumably, you also want 1.1.3 of `logback-core` too? If so, I'd recommend that you override the `logback.version` property, as [recommended in Spring Boot's documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-dependency-versions).

**Comment by JLLeitschuh** [comment] 2017-04-20 21:10
Right, I've tried that too, that doesn't always work, and it doesn't seem like there isn't a central location where the variables like `logback.version` are all declared and can quickly be looked up.

**Comment by wilkinsona** [comment] 2017-04-20 21:12
> Right, I've tried that too, that doesn't always work

Can you be more specific? AFAIK, it should always work

> it doesn't seem like there isn't a central location where the variables like logback.version are all declared and can quickly be looked up

They're all declared in [Spring Boot's bom](https://github.com/spring-projects/spring-boot/blob/v1.5.2.RELEASE/spring-boot-dependencies/pom.xml#L47-L193).

**Comment by JLLeitschuh** [comment] 2017-04-20 21:22
> They're all declared in Spring Boot's bom.

Thanks! That's really helpful!

> Can you be more specific? AFAIK, it should always work

I was having this same problem with `servlet-api.version`. For some reason setting it explicitly was totally ignored by gradle. I'll try it again.

Is there any way to get the`force` code to also override the BOM?
If I need to do this then I need to declare the version using the `logback.version` variable then I also need to use `force()` for other non-boot projects in the build.

I would have thought that:
```kotlin
dependencyManagement {
    resolutionStrategy {
        // Same list of forced dependencies
        force("... forced dependencies ....")
    }
}
```
would have solved this problem. Why does the API allow for configuring the `dependencyManagement` resolution strategy if it really doesn't work?

**Comment by JLLeitschuh** [comment] 2017-04-20 21:41
Also, being able to use the resolution strategy correctly would let a user do things like this:
```kotlin
resolutionStrategy {
        eachDependency {
            fun resolver(group: String, version: String) {
                if (requested.group == group) {
                    useTarget("${requested.group}:${requested.name}:$version")
                }
            }
            resolver("org.slf4j", "1.7.2")
            resolver("ch.qos.logback", logbackVersion)
            // ect...
        }
}
```
which is a really helpful bit of code to have.
I have `failOnVersionConflict()` configured on all of my project's configurations because I want to be 100% certain that developers know when there is a version conflict and give them the ability to intelligently and intentionally pick the version of the dependency they want.

**Comment by wilkinsona** [comment] 2017-04-21 08:18
> Is there any way to get theforce code to also override the BOM?

Looking into how `force` works, it would appear that, among all resolution strategies using `force`, the first one will win. However, any resolution strategy that uses `eachDependency` can change a forced version and among those that do, the last one will win. The dependency management plugin uses `eachDependency` which is why you see `force` apparently being ignored.

Here's a simple example:

```groovy
apply plugin: 'java'

configurations.all {
	resolutionStrategy {
		// Last eachDependency wins
		eachDependency { details ->
			if (details.target.group == 'commons-logging') {
				details.useVersion('1.1.2')
			}
		}
		eachDependency { details ->
			if (details.target.group == 'commons-logging') {
				details.useVersion('1.1.3')
			}
		}
		// Overriden by either eachDependency above
		force 'commons-logging:commons-logging:1.1.1'
	}
}

repositories {
	mavenCentral()
}

dependencies {
	compile 'org.springframework:spring-core:4.3.8.RELEASE'
}
```

> Is there any way to get theforce code to also override the BOM?

Not at the moment. This plugin could be changed to skip dependencies that have a forced version. However, there's a small chance that it would be a breaking change for some users, so it'll have to be done with care and may have to wait for 1.1.

>  Why does the API allow for configuring the dependencyManagement resolution strategy if it really doesn't work?

As far as I know, it does work. Judging by your example above, the problem is that you're not using it as intended. The `dependencyManagement` `resolutionStrategy` controls the strategy for resolving imported Maven boms. This is [described in the README](https://github.com/spring-gradle-plugins/dependency-management-plugin#configuring-the-dependency-management-resolution-strategy).

> which is a really helpful bit of code to have

That code is effectively rolling your own dependency management. Given that you've applied this plugin, why would you want to do that rather than using it?

**Comment by JLLeitschuh** [comment] 2017-04-21 14:19
> That code is effectively rolling your own dependency management. Given that you've applied this plugin, why would you want to do that rather than using it?

Because I want to get the benefits of spring boot (being able to boot and create WAR/JAR) but also be able to declare my own dependencies.
If I just apply the spring boot plugin my ability to control dependencies goes out the window. I was hoping to use this plugin to wrest control back over my dependency management.

**Comment by JLLeitschuh** [comment] 2017-04-21 14:35
This does indeed fix my problem:
```kotlin
eachDependency {
    fun resolver(group: String, version: String) {
        if (target.group == group) {
            useVersion(version)
        }
    }
    fun trueForce(group : String, name: String, version : String) {
        if (target.group == group && target.name == name) {
            useVersion(version)
        }
    }
    resolver("org.springframework", springVersion)
    resolver("org.slf4j", "1.7.2")
    resolver("ch.qos.logback", logbackVersion)
    trueForce("javax.servlet", "javax.servlet-api", javaxServletApiVersion)
}
```
I have this block of force code evaluated both in my root `allProjects` block but because the plugin is applied in a subproject I evaluate the function again with it's resolver in the subproject and everything seems to be being forced to the versions I want correctly now.

**Comment by wilkinsona** [comment] 2017-04-24 15:58
That's good news, thanks for following up. I think all that remains here is to avoid applying dependency management to a dependency that has had its version forced. That could be a breaking change for some so it'll either need to wait for 1.1 (at the earliest) or, alternatively, it could be disabled by default with an option to turn it on. The default could then change in 1.1.

**Comment by rupebac** [comment] 2019-04-08 09:10
guys, I am having another problem somewhat related with this:

forced dependencies, they do not get the version written in the generated pom.xml 

is this normal or expected?

**Comment by wilkinsona** [comment] 2019-04-15 09:13
@rupebac Forced dependencies are a Gradle feature. If the forced version isn't making it into the pom, that sounds like a Gradle problem rather than an issue with this plugin.

**Comment by wilkinsona** [comment] 2022-06-30 19:48
Superseded by #330.

**Closed by wilkinsona** 2022-06-30 19:48 UTC
Labels: type: enhancement
