### ISSUE TITLE
Subproject not able to resolve versions of common module

### ISSUE THREAD

**Issue by LethiferousMoose** [spring-gradle-plugins/dependency-management-plugin#308] opened 2021-09-08 16:13 UTC
We have a multi-project setup with a common module and various subprojects that rely on the common project:
```
project
│   build.gradle
│   settings.gradle  
│
└───common
│   │   src
│   │   build.gradle
│   │
└───subproject
     │   src
     │   build.gradle
```

The issue I am seeing is that when I have dependencies in common that are transitive to things that depend on it, the subprojects cannot resolve the version of the project they depend on. I've attached a sample project that demonstrates the issue.

```
> Task :test-subproject:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test-subproject:compileJava'.
> Could not resolve all files for configuration ':test-subproject:compileClasspath'.
   > Could not find co.elastic.apm:apm-agent-api:.
     Required by:
         project :test-subproject > project :test-common
```

The only workaround I was able to find was to add a dependency block in each subproject to map the version, but that kind of defeats the point of using the plugin...

[SpringDep.zip](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/7130301/SpringDep.zip)

**Comment by wilkinsona** [comment] 2021-09-08 17:16
Duplicate of #94.

**Closed by wilkinsona** 2021-09-08 17:16 UTC
Labels: status: waiting-for-triage
