### ISSUE TITLE
Versions not resolved with java 9

### ISSUE THREAD

**Issue by makigumo** [spring-gradle-plugins/dependency-management-plugin#187] opened 2017-09-24 17:06 UTC
Hello!

When using Java 9 it looks like that some versions are not resolved.

Here are some steps to reproduce:

#### Sample project
```sh
$ curl https://start.spring.io/starter.zip -d dependencies=web,thymeleaf -d type=gradle-build -d baseDir=dep-test -d bootVersion=2.0.0.M4 -d packaging=war | tar -xzvf -
$ cd dep-test
```

#### Run with Java 9 (fails to resolve dependencies)
```sh
$ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/ gradle --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/local/Cellar/gradle/4.2/libexec/lib/groovy-all-2.4.11.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9 (Oracle Corporation 9+181)
OS:           Mac OS X 10.12.6 x86_64

$ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/ gradle build

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find org.springframework.boot:spring-boot-starter-thymeleaf:.
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-thymeleaf//spring-boot-starter-thymeleaf-.pom
      https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-thymeleaf//spring-boot-starter-thymeleaf-.jar
      https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-starter-thymeleaf//spring-boot-starter-thymeleaf-.pom
      https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-starter-thymeleaf//spring-boot-starter-thymeleaf-.jar
      https://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-thymeleaf//spring-boot-starter-thymeleaf-.pom
      https://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-thymeleaf//spring-boot-starter-thymeleaf-.jar
  Required by:
      project :
> Could not find org.springframework.boot:spring-boot-starter-web:.
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
1 actionable task: 1 executed
```

#### Run with Java 1.8 (runs correctly)

```sh
$ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/ gradle --version

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64

$ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/ gradle build

> Task :test
2017-09-24 19:00:45.481  INFO 33897 --- [       Thread-5] o.s.w.c.s.GenericWebApplicationContext   : Closing org.springframework.web.context.support.GenericWebApplicationContext@5078624a: startup date [Sun Sep 24 19:00:43 CEST 2017]; root of context hierarchy


BUILD SUCCESSFUL in 9s
5 actionable tasks: 5 executed
```

Thanks.

**Comment by wilkinsona** [comment] 2017-09-25 05:02
Duplicate of https://github.com/spring-projects/spring-boot/issues/10049.

**Closed by wilkinsona** 2017-09-25 05:02 UTC

**Comment by flozano** [comment] 2017-09-25 13:29
This is a spring-boot specific issue? or something to be taken into account if using this plugin with java 9 without spring boot?

**Comment by wilkinsona** [comment] 2017-09-25 13:33
It's specific to Spring Boot
