### ISSUE TITLE
Cannot use dependencyManagement.importedProperties when defining additional dependency management

### ISSUE THREAD

**Issue by wujek-srujek** [spring-gradle-plugins/dependency-management-plugin#56] opened 2015-07-26 15:46 UTC
I have a project with submodules. The root module applies the dependency management plugin and imports the spring-boot-dependencies BOM for the submodules. One of the submodules ('boot') applies the 'spring-boot' plugin (the code for the build files below). Now, when the dependencyManagement.importedProperties map is used before the apply plugin: 'spring-boot', the build crashes with the error from the topic. This doesn't happen when the line is moved below the plugin application, or when the 'spring-boot' plugin is not imported at all.
I'm reporting it here as I know that spring-boot recently migrated to this plugin for dependency management.

settings.gradle:

```
include 'no-boot'
include 'boot'
rootProject.name = 'dep-test'
```

build.gradle:

```
ext {
    springBootVersion = '1.3.0.M2'
}

assert JavaVersion.current().java8Compatible:
        "At least Java $javaVersion is required, current JVM is ${JavaVersion.current()}"

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:0.5.2.RELEASE'
    }
}

subprojects {
    repositories {
        jcenter()
    }

    group = 'com.dep.test'

    apply plugin: 'groovy'
    apply plugin: 'io.spring.dependency-management'

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:$springBootVersion"
        }
        dependencies {
            dependency 'org.glassfish.jersey.core:jersey-client:2.19'
        }
    }

    defaultTasks = ['clean', 'build']
}

defaultTasks = subprojects.clean*.path + subprojects.build*.path

task wrapper(type: Wrapper) {
    description = 'Defines the common gradle distribution for this project.'
    gradleVersion = '2.5'
}
```

no-boot/build.gradle:

```
println dependencyManagement.importedProperties['jersey.version']
```

bot/build.gradle:

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:$springBootVersion"
    }
}

println dependencyManagement.importedProperties['jersey.version']

apply plugin: 'spring-boot'

dependencies {
    compile project(':no-boot')

    compile 'org.springframework.boot:spring-boot-starter'
    runtime 'org.springframework.boot:spring-boot-devtools'
}
```

The workaround of putting the reference to the imported properties before the plugin does not work for my use case, which is:
- I apply the dependency management plugin for all submodules so that they can use the blessed Boot dependency versions
- however, when something is not defined in the dependencyManagement, I would like to be able to define it myself (in the root module, for all submodules to use)

So, I would like my build.gradle to look like (I only include the subproject closure this time, the rest stays the same):

```
 subprojects {
    repositories {
        jcenter()
    }

    group = 'com.dep.test'

    apply plugin: 'groovy'
    apply plugin: 'io.spring.dependency-management'

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:$springBootVersion"
        }
        dependencies {
            dependency "org.glassfish.jersey.core:jersey-client:${dependencyManagement.importedProperties['jersey.version']}"
        }
    }

    defaultTasks = ['clean', 'build']
}
```

So, I will generally use Spring Boot versions in the modules, also for artifacts they didn't include in their dependency management, but they do define the compatible version for.

The issue is, that the reference to the imported properties in build.gradle happens before the spring-boot plugin is applied in the submodule, and crashes with the error in the title.

Is this a bug or am I doing something very unorthodox here?

**Comment by wilkinsona** [comment] 2015-07-27 09:37
The problem is that accessing `dependencyManagement.importedProperties['jersey.version']` requires the plugin to figure out all of the imported properties. This is happening in the evaluation phase of the main `build.gradle` script. To figure out the imported properties the plugin has to resolve the configuration that holds all of the imported bom dependencies. Beyond this point, no more bom imports can be made as a resolved configuration cannot be modified. Subsequently, when `boot`'s `gradle.gradle` is evaluated the Spring Boot plugin is applied. It tries to apply its default dependency management import which fails as the configuration has already been resolved.

The dependency management plugin could, perhaps, use a new configuration for bom imports when it detects that the current configuration has been resolved. However, I'm concerned that this would be difficult to reason about, and may cause some strange and unwanted side-effects. It'll certainly require more thought before I can convince myself that it's the right thing to do.

In the meantime, I believe you can avoid the problem you're seeing by deferring the use of `dependencyManagement.importedProperties` until after project evaluation has completed by using `afterEvaluate`:

```groovy
subprojects {
	afterEvaluate {
		dependencyManagement {
			dependencies {
				dependency "org.glassfish.jersey.core:jersey-client:${dependencyManagement.importedProperties['jersey.version']}"
			}
		}
	}
}
```

**Comment by manikandanrs** [comment] 2016-01-19 18:30
Hi, 

I am very new to gradle and trying to use this plugin to import this [BOM](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-bom/pom.xml). I am getting the same error. Is there a workaround temporarily while the plugin is fixed. 

Here is my build.gradle configuration

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.5.4.RELEASE"
    }
}

apply plugin: "io.spring.dependency-management"

dependencyManagement {
    imports {
        mavenBom 'com.amazonaws:aws-java-sdk-bom:1.10.47'
    }
}

dependencies {
    compile 'com.amazonaws:aws-java-sdk-s3'
    testCompile group: 'junit', name: 'junit', version: '4.11'
}
```

**Comment by wilkinsona** [comment] 2016-01-19 19:14
@manikandanrs That `build.gradle` doesn't produce the problem described in this issue. It's also incomplete. I had to apply the Java plugin and add Maven Central as a repository before it would work. Here's what I ended up with:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.5.4.RELEASE"
    }
}

apply plugin: "io.spring.dependency-management"
apply plugin: "java"

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'com.amazonaws:aws-java-sdk-bom:1.10.47'
    }
}

dependencies {
    compile 'com.amazonaws:aws-java-sdk-s3'
    testCompile group: 'junit', name: 'junit', version: '4.11'
}
```

**Comment by manikandanrs** [comment] 2016-01-19 19:39
Awesome. This worked. Thanks for the quick response.

**Comment by sinjihn** [comment] 2016-01-24 09:31
Here's my gradle file:

    buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
    	classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.2.RELEASE")
        classpath("org.springframework:spring-context:4.2.4.RELEASE")
        classpath("io.spring.gradle:dependency-management-plugin:0.5.4.RELEASE")
       
    }
}

apply plugin: "io.spring.dependency-management"
apply plugin: 'spring-boot'
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'

jar {
    baseName = 'Nudger-ML'
    version =  '0.1.0'
}

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8



dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    testCompile("junit:junit")
 	compile fileTree(dir: 'libs', include: '*.jar')
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}

and i'm getting the same issue. i've been trying to use gradle and spring to start a restful service, but i changed the  classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.2.RELEASE") from 1.2.6 recently and now i'm getting this error.

**Comment by gigi888** [comment] 2016-03-22 14:13
Thank you, wilkinsona. It helped me too!

**Comment by ePaul** [comment] 2016-06-06 16:33
I just had the same error message ... after some experimenting (removing arbitrary lines from the build.gradle) I got a different error message, and I found it was caused by non-trusted certificates for Maven Central and/or Spring.io's repository. (I had removed several root certificates from my local computer's certificate store, i.e. JVM/lib/security/cacerts).

The error message really doesn't help for such a diagnosis.

**Comment by wilkinsona** [comment] 2016-06-13 09:50
@ePaul If non-trusted certificates were the root cause, then you had a different problem to that one described by @wujek-srujek. I believe what you were hitting was #81. Do you get a better error message with 0.5.7.RELEASE?

**Comment by ananthan31** [comment] 2016-06-13 11:48
I have a very simple `build.gradle` file which I have created following [Spring cloud website](https://cloud.spring.io/spring-cloud-netflix/).

```
plugins {
  id "io.spring.dependency-management" version "0.5.7.RELEASE"
}

apply plugin: "java"
apply plugin: "io.spring.dependency-management"

repositories {
    mavenCentral()
}

dependencyManagement {
     imports {
          mavenBom 'org.springframework.cloud:spring-cloud-netflix:1.1.2.RELEASE'
     }
}
dependencies {
    compile 'org.springframework.cloud:spring-cloud-starter-eureka'
}

```

When I run the `gradle build` command, I am getting the same error (below)
```
* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve org.springframework.cloud:spring-cloud-starter-eureka:.
  Required by:
      :foo:unspecified
   > Failed to resolve imported Maven boms: Cannot change dependencies of configuration 'detachedConfiguration1' after it has been resolved.
```

How do I resolve it?

**Comment by wilkinsona** [comment] 2016-06-13 13:23
@ananthan31 I'm struggling to figure out why Gradle's reporting the error the way that it is, but the root cause of the problem is that `org.springframework.cloud:spring-cloud-netflix:1.1.2.RELEASE` isn't available from Maven Central. You need to add `https://repo.spring.io/libs-release` as a Maven repository.

**Comment by ePaul** [comment] 2016-06-13 17:15
@wilkinsona I don't know which version we were using. I can't try this now, because I will not intentionally break my Java configuration again, and also our project switched back to Maven since then (for unrelated reasons).

I mainly added this here because this issue was one of the first Google hits for the error message, and it might help others with the same problem.

**Comment by alan-czajkowski** [comment] 2017-05-24 21:59
@ePaul switched back to Maven? :) yeah, I'm seriously considering switching from Gradle to Maven (as I've never seen such crazy struggles with Maven plugins, they just work -- I've done some crazy complex builds with Maven and never have I ever struggled like I do with Gradle, every day I encounter a new problem with Gradle)

**Comment by wilkinsona** [comment] 2018-09-19 09:40
A similar problem has also been reported in https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/193. I believe that they both have the same underlying cause and can hopefully be addressed with the same solution. #193 provides a more focussed discussion and description of the problem so I'm going to close this one as a duplicate.

**Closed by wilkinsona** 2018-09-19 09:40 UTC
